
import compiler.*;
import gui.Traduccion;

import java.io.*;
import java.util.logging.*;

import org.antlr.runtime.*;
import org.apache.bsf.BSFException;
import org.apache.bsf.BSFManager;

public class MainWin extends javax.swing.JFrame {

    public MainWin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        entrada = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        entrada.setColumns(20);
        entrada.setFont(new java.awt.Font("Tahoma", 1, 14));
        entrada.setRows(5);
        entrada.setText("leer (\"Entre la edad\",   ed, \"Diga un numero\", n).eeee(34, 5 div 3).lala;\n\nk <- 1;\ndesde i <- 7 hasta 1 con paso -2 hacer\ninicio\n    k <- k + 2;\nfin\n\nsi (5 > 21) entonces\ninicio\nmostrar(\"Ud entro la edad:\", ed, \"El doble de la edad es:\", 2*ed);\nfin\nsino\ninicio\nmostrar(\"Probando:\", 3);\nfin\n\n");
        jScrollPane1.setViewportView(entrada);

        jButton1.setMnemonic('E');
        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            CharStream input = new ANTLRStringStream(entrada.getText());

            RobotLexer lex = new RobotLexer(input);

            CommonTokenStream tokens = new CommonTokenStream(lex);

            //System.out.println("tokens="+tokens);

            RobotParser parser = new RobotParser(tokens);
            String data = parser.program();

//            Traduccion consola = new Traduccion();
//            consola.setTraduccion(data);
//            consola.setVisible(true);

            BSFManager.registerScriptingEngine("ruby",
                    "org.jruby.javasupport.bsf.JRubyEngine",
                    new String[]{"rb"});

            String st = rsc.TextLoader.getAllText(getClass().getResourceAsStream("/rsc/util.rb"));
            String toExec = "include Java \n" + st + data;
            System.out.println(toExec);
            new BSFManager().exec("ruby", "", 0, 0, toExec);

            if (false) {
                throw new BSFException("");
            }
        } catch (IOException ex) {
            Logger.getLogger(MainWin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BSFException ex) {
            Logger.getLogger(MainWin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RecognitionException ex) {
            Logger.getLogger(MainWin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainWin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea entrada;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
