package entradasalida;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class InputOutput extends javax.swing.JDialog {

    public InputOutput(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public InputOutput(String title) {
        this(null, true);
        setTitle(title);
    }

    public ArrayList<Object> getValores() {
        ArrayList<Object> res = new ArrayList<Object>();
        for (int i = 0; i < tabla.getModel().getRowCount(); i++) 
            res.add(tabla.getModel().getValueAt(i, 1));
        return res;
    }

    
    public void adicionarFila(String msg, Object dat) {

        Object[][] vals = new Object[tabla.getModel().getRowCount() + 1][2];

        for (int i = 0; i < tabla.getModel().getRowCount(); i++) {
            for (int j = 0; j < tabla.getModel().getColumnCount(); j++) {
                vals[i][j] = tabla.getModel().getValueAt(i, j);
            }
        }

        vals[tabla.getModel().getRowCount()][0] = msg;
        vals[tabla.getModel().getRowCount()][1] = dat.toString();


        tabla.setModel(new DefaultTableModelImpl(
                vals,
                new String[]{
            "Mensaje", "Dato"
        }));
    }

    public void adicionarMensaje(String msg) {

        Object[][] vals = new Object[tabla.getModel().getRowCount() + 1][2];

        for (int i = 0; i < tabla.getModel().getRowCount(); i++) {
            for (int j = 0; j < tabla.getModel().getColumnCount(); j++) {
                vals[i][j] = tabla.getModel().getValueAt(i, j);
            }
        }

        vals[tabla.getModel().getRowCount()][0] = msg;
        vals[tabla.getModel().getRowCount()][1] = "";


        tabla.setModel(new DefaultTableModelImpl(
                vals,
                new String[]{
            "Mensaje", "Dato"
        }));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Interfaz de entrada salida");
        setResizable(false);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mensaje", "Dato"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        jButton1.setMnemonic('A');
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

    private class DefaultTableModelImpl extends DefaultTableModel {

        public DefaultTableModelImpl(Object[][] data, Object[] columnNames) {
            super(data, columnNames);
        }
        Class[] types = new Class[]{java.lang.String.class, java.lang.String.class};
        boolean[] canEdit = new boolean[]{false, true};

        @Override
        public Class getColumnClass(int columnIndex) {
            return types[columnIndex];
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
        }
    }
}
