package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

public class Editor extends javax.swing.JDialog {

    private static final long serialVersionUID = -1206262349653949301L;

    private Editor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    JFileChooser fileSelector;
    MainGUI gui;
    public Editor(MainGUI gui) {
        this(null, false);
        
        this.gui = gui;
        
        fileSelector = new JFileChooser("./ejemplos/");
        ExampleFileFilter filter = new ExampleFileFilter();
        filter.addExtension("r");
        filter.setDescription("Instrucciones para el robot");
        fileSelector.setFileFilter(filter);
    }

    public void addSrcActionListener(ActionListener l) {
        btEjecutar.addActionListener(l);
    }

    public String getJRubySrc() {
        return JRSrcEditor.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuEmergente = new javax.swing.JPopupMenu();
        leer = new javax.swing.JMenuItem();
        salvar = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        JRSrcEditor = new javax.swing.JTextArea();
        btEjecutar = new javax.swing.JButton();
        btInit = new javax.swing.JButton();

        leer.setText("Cargar instrucciones desde fichero");
        leer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerActionPerformed(evt);
            }
        });
        menuEmergente.add(leer);

        salvar.setText("Salvar instrucciones");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        menuEmergente.add(salvar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Panel de Control");

        JRSrcEditor.setColumns(20);
        JRSrcEditor.setComponentPopupMenu(menuEmergente);
        JRSrcEditor.setFont(new java.awt.Font("Tahoma", 1, 14));
        JRSrcEditor.setRows(5);
        JRSrcEditor.setText("robot.darPaso;\n\nrobot.girarDerecha;\n\npasos <- 6;\n\ndesde i <- 1 hasta pasos hacer\ninicio\n robot.darPaso;\nfin\n\nrobot.girarIzquierda;\n\ndesde i <- 1 hasta 4 hacer\ninicio\n  robot.darPaso;\nfin\n\nrobot.abrirPuerta(puerta);\n\ndesde i <- 1 hasta 2 hacer\ninicio\n  robot.darPaso;\nfin\n\nrobot.darMediaVuelta;\n\nrobot.cerrarPuerta(puerta);\n\nrobot.darMediaVuelta;\n\ndesde i <- 1 hasta 2 hacer\ninicio\n  robot.darPaso;\nfin\n");
        jScrollPane1.setViewportView(JRSrcEditor);

        btEjecutar.setMnemonic('e');
        btEjecutar.setText("Ejecutar");
        btEjecutar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btInit.setText("Inicializar");
        btInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btInit, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btInit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void leerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerActionPerformed
        fileSelector.setDialogTitle("Escoja el fichero con las instrucciones para el robot");
        //fileSelector.setDialogType(JFileChooser.OPEN_DIALOG);

        if (fileSelector.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                BufferedReader input = new BufferedReader(new FileReader(fileSelector.getSelectedFile()));
                try {
                    JRSrcEditor.setText("");
                    String line = null;
                    while ((line = input.readLine()) != null) {
                        JRSrcEditor.append(line + "\n");
                    }
                } finally {
                    input.close();
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_leerActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        fileSelector.setDialogTitle("Diga el nombre del fichero que utlizará para salvar las instrucciones");
        //fileSelector.setDialogType(JFileChooser.OPEN_DIALOG);

        if (fileSelector.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            Writer output = null;

            try {
                output = new BufferedWriter(new FileWriter(fileSelector.getSelectedFile()));
                output.write(JRSrcEditor.getText());
             
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            finally {
                try {
                    output.close();
                } catch (IOException ex) {
                    Logger.getLogger(Editor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }//GEN-LAST:event_salvarActionPerformed

    private void btInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInitActionPerformed
        gui.resetState();
    }//GEN-LAST:event_btInitActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JRSrcEditor;
    private javax.swing.JButton btEjecutar;
    private javax.swing.JButton btInit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem leer;
    private javax.swing.JPopupMenu menuEmergente;
    private javax.swing.JMenuItem salvar;
    // End of variables declaration//GEN-END:variables
}
